"""
Phase 2: train the SentencePiece tokenizer for the Basque (eu) FUTO model.

Replicates the reference English tokenizer's structural layout:
  indices 0-3:    pad / bos / eos / unk
  indices 4-303:  300 user-defined symbols (declaration order = ID order)
                  - 4..27   <FUTO0>..<FUTO23>            (parity filler)
                  - 28..173 Basque common words           (146 slots)
                  - 174..176 <XBU> <XBC> <XEC>            (REQUIRED, name-looked-up)
                  - 177..181 <XC0>..<XC4>                 (parity, only XC0 used by Android)
                  - 182..207 <CHAR_A>..<CHAR_Z>           (REQUIRED, MUST be sequential)
                  - 208..263 more Basque common words     (56 slots)
                  - 264..303 emoji                         (40 slots)
  indices 304-559: byte fallback <0x00>..<0xFF> (256 slots, auto-generated by SP)
  indices 560+:    learned UNIGRAM pieces from corpus

The Basque content-slot word lists live in config/eu.py so this script stays
generic; only the structural assembly + training happen here.

Usage:
  uv run python -m scripts.tokenizer.train --corpus /workspace/corpora/clean --out tokenizer/spm_eu
"""
from __future__ import annotations
import argparse
import glob
import json
from pathlib import Path

import sentencepiece as spm

from config.eu import EMOJI, SLOT_28_173 as _SLOT_28_173, SLOT_208_263 as _SLOT_208_263
from scripts.lib.runconfig import load_config, pick

# SentencePiece whitespace marker (▁, U+2581). The `inverted_space` feature
# (treat_whitespace_as_suffix=True) means learned pieces attach space as a
# suffix; the user-defined content words below are given the same suffix so they
# behave like normal word+space tokens. Mirrors the English reference style.
SPACE = "▁"


def with_suffix(words: list[str]) -> list[str]:
    return [w + SPACE for w in words]


def _pad_to(words: list[str], n: int, start_index: int) -> list[str]:
    """Pad (or truncate) a content list to exactly n entries using <FUTO> filler."""
    words = list(words)
    if len(words) < n:
        words += [f"<FUTO{start_index + i}>" for i in range(n - len(words))]
    return words[:n]


# 146 content words (slots 28..173) + 56 (slots 208..263), space-suffixed.
SLOT_28_173 = with_suffix(_pad_to(_SLOT_28_173, 146, 28))
SLOT_208_263 = with_suffix(_pad_to(_SLOT_208_263, 56, 208))
assert len(SLOT_28_173) == 146, len(SLOT_28_173)
assert len(SLOT_208_263) == 56, len(SLOT_208_263)
assert len(EMOJI) == 40 and len(set(EMOJI)) == 40, "emoji count/unique mismatch"


def build_user_defined_symbols() -> list[str]:
    """Return exactly 300 symbols in the order they should be assigned IDs 4..303."""
    symbols: list[str] = []
    # 4..27 — FUTO0..FUTO23 filler
    symbols += [f"<FUTO{i}>" for i in range(24)]
    # 28..173 — 146 Basque common words
    symbols += SLOT_28_173
    # 174..176 — STRUCTURAL: required for xbu_char_autocorrect_v1
    symbols += ["<XBU>", "<XBC>", "<XEC>"]
    # 177..181 — XC0..XC4 (parity; only XC0 used by Android; declaring all 5 keeps room for future swipe)
    symbols += [f"<XC{i}>" for i in range(5)]
    # 182..207 — STRUCTURAL: <CHAR_A>..<CHAR_Z> MUST be 26 sequential IDs
    symbols += [f"<CHAR_{c}>" for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"]
    # 208..263 — 56 more Basque common words
    symbols += SLOT_208_263
    # 264..303 — 40 emoji
    symbols += EMOJI
    assert len(symbols) == 300, f"Expected 300 symbols, got {len(symbols)}"
    return symbols


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=None,
                    help="YAML config file (configs/phase2_tokenizer.yaml)")
    ap.add_argument("--mode", default="full", choices=["mini", "full"],
                    help="Which mode section to load from the config")
    ap.add_argument("--corpus", required=True, help="Glob or dir of plain-text shard files")
    ap.add_argument("--out", default="tokenizer/spm_eu", help="Output prefix (writes .model and .vocab)")
    ap.add_argument("--vocab-size", type=int, default=None,
                    help="Vocab size. Default: 4096 (see configs/phase2_tokenizer.yaml).")
    ap.add_argument("--input-sentence-size", type=int, default=None,
                    help="Number of sentences to sample for training.")
    args = ap.parse_args()

    cfg = load_config(args.config, args.mode)
    vocab_size = pick(args.vocab_size, cfg, "vocab_size", 4096)
    input_sentence_size = pick(args.input_sentence_size, cfg, "input_sentence_size", 10_000_000)

    # Resolve corpus glob
    corpus = Path(args.corpus)
    if corpus.is_dir():
        files = sorted(str(p) for p in corpus.glob("shard_*.txt"))
    else:
        files = sorted(glob.glob(args.corpus))
    if not files:
        raise SystemExit(f"No corpus shards found at {args.corpus}")
    print(f"Training on {len(files)} shard(s):")
    for f in files[:5]:
        print(f"  {f}")
    if len(files) > 5:
        print(f"  ... ({len(files) - 5} more)")

    assert vocab_size > 560, \
        f"vocab_size={vocab_size} too small: 560 slots are reserved (4 control + 300 structural + 256 byte-fallback)"

    user_defined = build_user_defined_symbols()
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out + ".user_defined.json").write_text(json.dumps(user_defined, ensure_ascii=False, indent=2))
    print(f"Wrote {args.out}.user_defined.json (300 symbols)")

    spm.SentencePieceTrainer.train(
        input=",".join(files),
        input_format="text",
        model_prefix=args.out,
        vocab_size=vocab_size,
        character_coverage=0.9995,
        model_type="unigram",  # match English reference; UNIGRAM suits Basque's agglutinative morphology
        treat_whitespace_as_suffix=True,    # `inverted_space` feature
        add_dummy_prefix=False,             # match reference: no leading ▁ before <XBC> corrected word
        remove_extra_whitespaces=False,     # match reference: preserve original whitespace
        user_defined_symbols=user_defined,  # 300 symbols at IDs 4..303
        pad_id=0, bos_id=1, eos_id=2, unk_id=3,  # match English reference
        input_sentence_size=input_sentence_size,
        shuffle_input_sentence=True,
        byte_fallback=True,
        max_sentence_length=4192,
        num_threads=8,
    )
    print(f"Wrote {args.out}.model and {args.out}.vocab")

    # Validate
    sp = spm.SentencePieceProcessor()
    sp.load(args.out + ".model")
    print(f"vocab_size={sp.get_piece_size()}")
    assert sp.get_piece_size() == vocab_size, "vocab size mismatch"

    # Structural assertions
    for name in ("<XBU>", "<XBC>", "<XEC>", "<XC0>"):
        i = sp.piece_to_id(name)
        assert i > 3, f"{name} not present (piece_to_id={i})"
        print(f"  {name} -> id {i}")

    # CHAR_A..CHAR_Z must be 26 sequential
    char_ids = [sp.piece_to_id(f"<CHAR_{c}>") for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"]
    print(f"  <CHAR_*> ids: {char_ids[0]}..{char_ids[-1]} (range {char_ids[0]}..{char_ids[0]+25})")
    assert char_ids == list(range(char_ids[0], char_ids[0] + 26)), \
        f"CHAR_A..Z not sequential: {char_ids}"

    # MorphAcc spot-check (morpheus-mamba tokenizer-fieldwork protocol)
    # At 4K the tokenizer should split roots from case suffixes.
    # At 15K+ it memorizes whole forms (surface-form regime = bad for Basque).
    #
    # NOTE: with treat_whitespace_as_suffix=True (inverted_space), standalone words
    # don't get a ▁ prefix — the ▁ is a suffix on the *previous* token. So we check
    # for the root with or without ▁, and the suffix in the remaining pieces.
    morph_tests = {
        "etxetik": ("etxe", "tik"),
        "etxera":  ("etxe", "ra"),
        "etxea":   ("etxe", "a"),
        "mendira": ("mendi", "ra"),
        "gizona":  ("gizon", "a"),
    }
    print("\n=== MorphAcc spot-check (expect root+suffix splits) ===")
    hits = 0
    for word, (root, suffix) in morph_tests.items():
        pieces = sp.encode_as_pieces(word)
        root_match = pieces[0] == root or pieces[0] == '▁' + root
        suffix_match = suffix in pieces[1:]
        ok = root_match and suffix_match
        hits += ok
        status = "✓ split" if ok else "✗ memorized/mis-split"
        print(f"  {word:10s} -> {pieces}  {status}")
    print(f"  MorphAcc spot-check: {hits}/{len(morph_tests)} split correctly")
    if hits < len(morph_tests) * 0.6:
        print("  ⚠ WARNING: MorphAcc < 60% — vocab may be too large for Basque morphology.")
        print("    Consider retraining with a smaller --vocab-size (see morpheus-mamba fieldwork).")

    # Whitespace-as-suffix smoke test
    sample = "Egun on, gaur egun ederra da ibiltzeko."
    pcs = sp.encode_as_pieces(sample)
    print(f"\n  sample pieces: {pcs}")

    # XBU autocorrect format round-trip
    s = "Euskara <XBU>ekarra<XBC>eskerra<XEC> da"
    ids = sp.encode_as_ids(s)
    decoded = sp.decode(ids)
    print(f"  XBU round-trip: {ids[:20]}... -> {decoded[:80]!r}")

    print("Tokenizer trained and validated.")


if __name__ == "__main__":
    main()
